export const defaultOpticsParams = {
  enabled: true,
  sourceX: -0.9,
  sourceY: -2.3,
  sourceZ: -2.8,
  sampleCountU: 25,
  sampleCountV: 38,
  reflectedLength: 8,
  missLength: 7,
  incidentVisible: true,
  reflectedVisible: true,
  missVisible: false,
  hitPointVisible: false,
  sourceVisible: true,
  show2DOverlay: true,
  centerSliceOnlyIn2D: true,
  rayOpacity: 0.85,
  incidentOpacity: 0.75,
  reflectedOpacity: 0.95,
  missOpacity: 0.25,
  maxRenderedRays: 800,
  maxTracedRays: 1800,
  freeze: false,
  restStatePreview: false
};
